---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git

- name: Clone mattermost-docker
  git:
    repo: https://github.com/mattermost/docker
    dest: "{{ mattermost_docker_install_path }}/mattermost"
    # version: "{{ mattermost_docker_version }}"
    force: yes

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ mattermost_docker_install_path }}/mattermost/docker-compose.yml"
    owner: root
    group: root
    mode: 0600
  no_log: yes

- name: Template systemd unit
  template:
    src: mattermost.service.j2
    dest: /etc/systemd/system/mattermost.service
    owner: root
    group: root
    mode: 0644
  register: unit

- name: Reload daemons
  systemd:
    daemon_reload: yes
  when: unit.changed

- name: Enable service
  systemd:
    name: mattermost.service
    enabled: yes

- name: Create dirs
  file:
    path: "{{ mattermost_docker_install_path }}/mattermost/volumes/app/mattermost/{{ item }}"
    state: directory
  loop:
    - config
    - data
    - logs
    - plugins
    - client
    - client/plugins
    - bleve-indexes

- name: Copy cert to matter
  copy:
    src: agroassist.ru.2023.cert.crt
    dest: "{{ mattermost_docker_install_path }}/mattermost/volumes/app/mattermost/config/cert.crt"
    owner: 2000
    group: 2000
    mode: 0644
  no_log: yes

- name: Copy cert to nginx
  copy:
    src: agroassist.ru.2023.cert.crt
    dest: "{{ mattermost_docker_install_path }}/mattermost/volumes/web/cert/cert.crt"
    owner: root
    group: root
    mode: 0644
  no_log: yes

- name: Copy key to matter
  copy:
    src: agroassist.ru.2023.key.crt
    dest: "{{ mattermost_docker_install_path }}/mattermost/volumes/app/mattermost/config/key.crt"
    owner: 2000
    group: 2000
    mode: 0600
  no_log: yes

- name: Copy key to nginx
  copy:
    src: agroassist.ru.2023.key.crt
    dest: "{{ mattermost_docker_install_path }}/mattermost/volumes/web/cert/key.crt"
    owner: root
    group: root
    mode: 0600
  no_log: yes

- name: create mattermost config
  template:
    src: config.json.j2
    dest: "{{ mattermost_docker_install_path }}/mattermost/volumes/app/mattermost/config/config.json"
    owner: 2000
    group: 2000
    mode: 0644
  no_log: yes

- name: Update volume directory permissions
  file:
    path: "{{ mattermost_docker_install_path }}/mattermost/volumes/app/mattermost/"
    state: directory
    owner: 2000
    group: 2000
    recurse: yes
  when: mattermost_docker_update_volume_permissions

- name: Start containers
  systemd:
    name: mattermost.service
    state: started